class BookInfo {
  final int id;
  final String name;
  final String abbreviation;
  final String testament;
  final int position;

  const BookInfo({
    required this.id,
    required this.name,
    required this.abbreviation,
    required this.testament,
    required this.position,
  });
}

final List<BookInfo> bibleBooks = [
  // AT
  BookInfo(
    id: 1,
    name: 'Génesis',
    abbreviation: 'Gn',
    testament: 'old',
    position: 1,
  ),
  BookInfo(
    id: 2,
    name: 'Éxodo',
    abbreviation: 'Ex',
    testament: 'old',
    position: 2,
  ),
  BookInfo(
    id: 3,
    name: 'Levítico',
    abbreviation: 'Lv',
    testament: 'old',
    position: 3,
  ),
  BookInfo(
    id: 4,
    name: 'Números',
    abbreviation: 'Nm',
    testament: 'old',
    position: 4,
  ),
  BookInfo(
    id: 5,
    name: 'Deuteronomio',
    abbreviation: 'Dt',
    testament: 'old',
    position: 5,
  ),
  BookInfo(
    id: 6,
    name: 'Josué',
    abbreviation: 'Jos',
    testament: 'old',
    position: 6,
  ),
  BookInfo(
    id: 7,
    name: 'Jueces',
    abbreviation: 'Jue',
    testament: 'old',
    position: 7,
  ),
  BookInfo(
    id: 8,
    name: 'Rut',
    abbreviation: 'Rt',
    testament: 'old',
    position: 8,
  ),
  BookInfo(
    id: 9,
    name: '1 Samuel',
    abbreviation: '1 S',
    testament: 'old',
    position: 9,
  ),
  BookInfo(
    id: 10,
    name: '2 Samuel',
    abbreviation: '2 S',
    testament: 'old',
    position: 10,
  ),
  BookInfo(
    id: 11,
    name: '1 Reyes',
    abbreviation: '1 R',
    testament: 'old',
    position: 11,
  ),
  BookInfo(
    id: 12,
    name: '2 Reyes',
    abbreviation: '2 R',
    testament: 'old',
    position: 12,
  ),
  BookInfo(
    id: 13,
    name: '1 Crónicas',
    abbreviation: '1 Cr',
    testament: 'old',
    position: 13,
  ),
  BookInfo(
    id: 14,
    name: '2 Crónicas',
    abbreviation: '2 Cr',
    testament: 'old',
    position: 14,
  ),
  BookInfo(
    id: 15,
    name: 'Esdras',
    abbreviation: 'Esd',
    testament: 'old',
    position: 15,
  ),
  BookInfo(
    id: 16,
    name: 'Nehemías',
    abbreviation: 'Neh',
    testament: 'old',
    position: 16,
  ),
  BookInfo(
    id: 17,
    name: 'Ester',
    abbreviation: 'Est',
    testament: 'old',
    position: 17,
  ),
  BookInfo(
    id: 18,
    name: 'Job',
    abbreviation: 'Job',
    testament: 'old',
    position: 18,
  ),
  BookInfo(
    id: 19,
    name: 'Salmos',
    abbreviation: 'Sal',
    testament: 'old',
    position: 19,
  ),
  BookInfo(
    id: 20,
    name: 'Proverbios',
    abbreviation: 'Pr',
    testament: 'old',
    position: 20,
  ),
  BookInfo(
    id: 21,
    name: 'Eclesiastés',
    abbreviation: 'Ec',
    testament: 'old',
    position: 21,
  ),
  BookInfo(
    id: 22,
    name: 'Cantares',
    abbreviation: 'Cnt',
    testament: 'old',
    position: 22,
  ),
  BookInfo(
    id: 23,
    name: 'Isaías',
    abbreviation: 'Is',
    testament: 'old',
    position: 23,
  ),
  BookInfo(
    id: 24,
    name: 'Jeremías',
    abbreviation: 'Jer',
    testament: 'old',
    position: 24,
  ),
  BookInfo(
    id: 25,
    name: 'Lamentaciones',
    abbreviation: 'Lam',
    testament: 'old',
    position: 25,
  ),
  BookInfo(
    id: 26,
    name: 'Ezequiel',
    abbreviation: 'Ez',
    testament: 'old',
    position: 26,
  ),
  BookInfo(
    id: 27,
    name: 'Daniel',
    abbreviation: 'Dn',
    testament: 'old',
    position: 27,
  ),
  BookInfo(
    id: 28,
    name: 'Oseas',
    abbreviation: 'Os',
    testament: 'old',
    position: 28,
  ),
  BookInfo(
    id: 29,
    name: 'Joel',
    abbreviation: 'Jl',
    testament: 'old',
    position: 29,
  ),
  BookInfo(
    id: 30,
    name: 'Amós',
    abbreviation: 'Am',
    testament: 'old',
    position: 30,
  ),
  BookInfo(
    id: 31,
    name: 'Abdías',
    abbreviation: 'Abd',
    testament: 'old',
    position: 31,
  ),
  BookInfo(
    id: 32,
    name: 'Jonás',
    abbreviation: 'Jon',
    testament: 'old',
    position: 32,
  ),
  BookInfo(
    id: 33,
    name: 'Miqueas',
    abbreviation: 'Miq',
    testament: 'old',
    position: 33,
  ),
  BookInfo(
    id: 34,
    name: 'Nahúm',
    abbreviation: 'Nah',
    testament: 'old',
    position: 34,
  ),
  BookInfo(
    id: 35,
    name: 'Habacuc',
    abbreviation: 'Hab',
    testament: 'old',
    position: 35,
  ),
  BookInfo(
    id: 36,
    name: 'Sofonías',
    abbreviation: 'Sof',
    testament: 'old',
    position: 36,
  ),
  BookInfo(
    id: 37,
    name: 'Hageo',
    abbreviation: 'Hag',
    testament: 'old',
    position: 37,
  ),
  BookInfo(
    id: 38,
    name: 'Zacarías',
    abbreviation: 'Zac',
    testament: 'old',
    position: 38,
  ),
  BookInfo(
    id: 39,
    name: 'Malaquías',
    abbreviation: 'Mal',
    testament: 'old',
    position: 39,
  ),
  // NT
  BookInfo(
    id: 40,
    name: 'Mateo',
    abbreviation: 'Mt',
    testament: 'new',
    position: 1,
  ),
  BookInfo(
    id: 41,
    name: 'Marcos',
    abbreviation: 'Mc',
    testament: 'new',
    position: 2,
  ),
  BookInfo(
    id: 42,
    name: 'Lucas',
    abbreviation: 'Lc',
    testament: 'new',
    position: 3,
  ),
  BookInfo(
    id: 43,
    name: 'Juan',
    abbreviation: 'Jn',
    testament: 'new',
    position: 4,
  ),
  BookInfo(
    id: 44,
    name: 'Hechos',
    abbreviation: 'Hch',
    testament: 'new',
    position: 5,
  ),
  BookInfo(
    id: 45,
    name: 'Romanos',
    abbreviation: 'Ro',
    testament: 'new',
    position: 6,
  ),
  BookInfo(
    id: 46,
    name: '1 Corintios',
    abbreviation: '1 Co',
    testament: 'new',
    position: 7,
  ),
  BookInfo(
    id: 47,
    name: '2 Corintios',
    abbreviation: '2 Co',
    testament: 'new',
    position: 8,
  ),
  BookInfo(
    id: 48,
    name: 'Gálatas',
    abbreviation: 'Gá',
    testament: 'new',
    position: 9,
  ),
  BookInfo(
    id: 49,
    name: 'Efesios',
    abbreviation: 'Ef',
    testament: 'new',
    position: 10,
  ),
  BookInfo(
    id: 50,
    name: 'Filipenses',
    abbreviation: 'Flp',
    testament: 'new',
    position: 11,
  ),
  BookInfo(
    id: 51,
    name: 'Colosenses',
    abbreviation: 'Col',
    testament: 'new',
    position: 12,
  ),
  BookInfo(
    id: 52,
    name: '1 Tesalonicenses',
    abbreviation: '1 Ts',
    testament: 'new',
    position: 13,
  ),
  BookInfo(
    id: 53,
    name: '2 Tesalonicenses',
    abbreviation: '2 Ts',
    testament: 'new',
    position: 14,
  ),
  BookInfo(
    id: 54,
    name: '1 Timoteo',
    abbreviation: '1 Ti',
    testament: 'new',
    position: 15,
  ),
  BookInfo(
    id: 55,
    name: '2 Timoteo',
    abbreviation: '2 Ti',
    testament: 'new',
    position: 16,
  ),
  BookInfo(
    id: 56,
    name: 'Tito',
    abbreviation: 'Tit',
    testament: 'new',
    position: 17,
  ),
  BookInfo(
    id: 57,
    name: 'Filemón',
    abbreviation: 'Flm',
    testament: 'new',
    position: 18,
  ),
  BookInfo(
    id: 58,
    name: 'Hebreos',
    abbreviation: 'Heb',
    testament: 'new',
    position: 19,
  ),
  BookInfo(
    id: 59,
    name: 'Santiago',
    abbreviation: 'Stg',
    testament: 'new',
    position: 20,
  ),
  BookInfo(
    id: 60,
    name: '1 Pedro',
    abbreviation: '1 P',
    testament: 'new',
    position: 21,
  ),
  BookInfo(
    id: 61,
    name: '2 Pedro',
    abbreviation: '2 P',
    testament: 'new',
    position: 22,
  ),
  BookInfo(
    id: 62,
    name: '1 Juan',
    abbreviation: '1 Jn',
    testament: 'new',
    position: 23,
  ),
  BookInfo(
    id: 63,
    name: '2 Juan',
    abbreviation: '2 Jn',
    testament: 'new',
    position: 24,
  ),
  BookInfo(
    id: 64,
    name: '3 Juan',
    abbreviation: '3 Jn',
    testament: 'new',
    position: 25,
  ),
  BookInfo(
    id: 65,
    name: 'Judas',
    abbreviation: 'Jud',
    testament: 'new',
    position: 26,
  ),
  BookInfo(
    id: 66,
    name: 'Apocalipsis',
    abbreviation: 'Ap',
    testament: 'new',
    position: 27,
  ),
];

final Map<int, BookInfo> booksById = {for (final b in bibleBooks) b.id: b};
final Map<String, BookInfo> booksByName = {
  for (final b in bibleBooks) b.name.toLowerCase(): b,
};
final Map<String, BookInfo> booksByAbbr = {
  for (final b in bibleBooks) b.abbreviation.toLowerCase(): b,
};

final Map<int, String> bookSummaries = {
  1: 'Génesis narra los orígenes: la creación del universo, el hombre, el pecado y el pacto de Dios con Abraham, Isaac y Jacob. Cubre desde Adán hasta José en Egipto, estableciendo las bases de la historia de la redención.',
  2: 'Éxodo relata la liberación de Israel de la esclavitud en Egipto mediante Moisés, los diez plagas, la entrega de la Ley en el Sinaí y la construcción del Tabernáculo, donde Dios habita en medio de su pueblo.',
  3: 'Levítico es el manual de santidad para Israel: instrucciones sobre sacrificios, sacerdocio, pureza ceremonial, el Día de la Expiación y las leyes que separaban al pueblo como santo ante Dios.',
  4: 'Números describe el peregrinaje de Israel por el desierto durante 40 años, incluyendo el censo del pueblo, las rebeliones contra Moisés, la serpiente de bronce y la preparación para entrar a Canaán.',
  5: 'Deuteronomio contiene los discursos finales de Moisés recordando la Ley y renovando el pacto con la nueva generación antes de entrar a la Tierra Prometida, enfatizando el amor y la obediencia a Dios.',
  6: 'Josué narra la conquista de Canaán bajo el liderazgo de Josué, incluyendo la caída de Jericó, las campañas militares y la distribución de la tierra entre las doce tribus de Israel.',
  7: 'Jueces relata el ciclo repetitivo de pecado, opresión, arrepentimiento y liberación a través de jueces levantados por Dios, como Gedeón, Débora y Sansón, durante un período de decadencia espiritual.',
  8: 'Rut es una historia de amor y redención ambientada en tiempos de los jueces. Rut, una moabita, demuestra lealtad a su suegra Noemí y se convierte en antepasada del rey David.',
  9: '1 Samuel cubre la transición de Israel de una teocracia a una monarquía, con los profetas Samuel, el reinado fallido de Saúl y la unción de David como el rey según el corazón de Dios.',
  10: '2 Samuel sigue el reinado de David sobre Israel, sus victorias militares, el pacto davídico, su grave pecado con Betsabé y las consecuencias trágicas en su familia, incluyendo la rebelión de Absalón.',
  11: '1 Reyes narra los reinados de Salomón y la división del reino después de su muerte, alternando entre los reyes del norte (Israel) y del sur (Judá), con el ministerio de Elías el profeta.',
  12: '2 Reyes continúa la historia de los reinos divididos hasta su caída: Israel conquistado por Asiria y Judá por Babilonia, destacando el ministerio de Eliseo y los profetas que llamaban al arrepentimiento.',
  13: '1 Crónicas repasa la historia desde Adán hasta David, enfocándose en el linaje real de Judá y preparando el contexto para el reinado de David y sus preparativos para la construcción del Templo.',
  14: '2 Crónicas cubre desde Salomón hasta el exilio babilónico, destacando a los reyes de Judá que siguieron a Dios y las reformas religiosas, especialmente bajo Ezequías y Josías.',
  15: 'Esdras relata el regreso de los exiliados judíos de Babilonia y la reconstrucción del Templo en Jerusalén bajo Zorobabel y Esdras, quien restauró la enseñanza de la Ley.',
  16: 'Nehemías narra la reconstrucción de los muros de Jerusalén y las reformas espirituales lideradas por Nehemías, enfrentando oposición externa y problemas internos para restaurar la comunidad.',
  17: 'Ester cuenta cómo una joven judía se convierte en reina de Persia y salva a su pueblo del genocidio planeado por Amán, demostrando la providencia de Dios sin mencionarlo explícitamente.',
  18: 'Job explora el tema del sufrimiento inocente. Job pierde todo pero mantiene su fe, debatiendo con sus amigos sobre la justicia de Dios, hasta que Dios mismo responde y restaura a Job.',
  19: 'Salmos es una colección de 150 poemas y canciones que expresan toda la gama de emociones humanas: alabanza, adoración, lamento, acción de gracias y confianza en Dios, usados en el culto de Israel.',
  20: 'Proverbios es una colección de dichos sabios que enseñan cómo vivir con temor de Dios, cubriendo temas como la disciplina, el trabajo, las relaciones, el dinero y el habla.',
  21: 'Eclesiastés reflexiona sobre el sentido de la vida bajo el sol, concluyendo que todo es vanidad sin Dios. El autor invita a temer a Dios y disfrutar la vida como un don divino.',
  22: 'Cantares (Cantar de los Cantares) es un poema de amor entre un esposo y su esposa, celebrando la belleza del amor conyugal como un regalo de Dios.',
  23: 'Isaías es un libro profético que anuncia juicio contra Judá y las naciones, pero también promete esperanza mesiánica: el nacimiento del Emmanuel, el siervo sufriente y un nuevo cielo y tierra.',
  24: 'Jeremías advierte sobre el juicio inminente de Babilonia contra Judá, llamando al arrepentimiento. Incluye la promesa del nuevo pacto escrito en los corazones.',
  25: 'Lamentaciones es una serie de poemas que lloran la destrucción de Jerusalén por Babilonia, expresando profundo dolor pero también esperanza en la misericordia de Dios.',
  26: 'Ezequiel profetiza a los exiliados en Babilonia sobre el juicio de Israel y las naciones, y ofrece visión de restauración: huesos secos que reviven, el nuevo Templo y la gloria de Dios.',
  27: 'Daniel narra las experiencias de Daniel y sus amigos en Babilonia, manteniéndose fieles a Dios en medio de la adversidad. Incluye visiones proféticas sobre los reinos mundiales y el Reino de Dios.',
  28: 'Oseas usa su matrimonio con una mujer infiel como símbolo del amor de Dios por Israel a pesar de su idolatría, llamando al arrepentimiento y prometiendo restauración.',
  29: 'Joel anuncia un juicio devastador (plaga de langostas) como advertencia del Día del Señor, y promete el derramamiento del Espíritu Santo sobre todo el pueblo.',
  30: 'Amós denuncia la injusticia social y la hipocresía religiosa en Israel, declarando que el verdadero culto requiere justicia y rectitud, y anuncia restauración futura.',
  31: 'Abdías es el libro más corto del AT, profetizando el juicio contra Edom por su violencia contra Judá, y la restauración del pueblo de Dios.',
  32: 'Jonás narra la desobediencia y arrepentimiento del profeta Jonás, quien finalmente lleva el mensaje de arrepentimiento a Nínive, mostrando la misericordia de Dios hacia todas las naciones.',
  33: 'Miqueas denuncia la corrupción en Judá e Israel, anuncia el juicio y promete esperanza: el nacimiento del gobernante en Belén y un reino de paz eterna.',
  34: 'Nahúm profetiza la caída de Nínive (capital de Asiria), consolando a Judá con la noticia de que Dios es justo y vengará a sus enemigos.',
  35: 'Habacuc cuestiona a Dios sobre el sufrimiento y la injusticia, aprendiendo que el justo vivirá por su fe, y concluye con una hermosa declaración de confianza en Dios.',
  36: 'Sofonías anuncia el Día del Señor como juicio contra Judá y las naciones, pero termina con promesas de restauración y gozo para el remanente fiel.',
  37: 'Hageo motiva al pueblo a reconstruir el Templo después del exilio, recordándoles que poner a Dios en primer lugar trae bendición.',
  38: 'Zacarías combina visiones simbólicas con mensajes proféticos sobre la restauración de Jerusalén y el futuro mesiánico, incluyendo la entrada triunfal del Rey humilde.',
  39: 'Malaquías confronta la apatía espiritual y la corrupción sacerdotal después del exilio, llamando a la fidelidad en los diezmos y anunciando la venida del mensajero del pacto.',
  40: 'Mateo presenta a Jesús como el Mesías prometido y el cumplimiento de las profecías del AT. Incluye el Sermón del Monte, las parábolas del Reino y la Gran Comisión.',
  41: 'Marcos es el evangelio más dinámico, presentando a Jesús como el Siervo de Dios en acción. Enfatiza los milagros, el sufrimiento del Hijo del Hombre y el llamado al discipulado.',
  42: 'Lucas es un relato histórico detallado que presenta a Jesús como el Salvador de toda la humanidad. Destaca la compasión por los marginados, las mujeres y los pobres.',
  43: 'Juan presenta a Jesús como el Hijo de Dios y el Verbo hecho carne. Contiene los discursos más profundos de Jesús, siete señales milagrosas y el propósito: que creamos y tengamos vida.',
  44: 'Hechos narra el nacimiento de la iglesia mediante el poder del Espíritu Santo, desde Jerusalén hasta Roma, siguiendo el ministerio de Pedro y Pablo.',
  45: 'Romanos es la exposición más completa del evangelio: la justificación por la fe, la santificación, la soberanía de Dios y la vida práctica del creyente en comunidad.',
  46: '1 Corintios aborda problemas en la iglesia de Corinto: divisiones, inmoralidad, el uso de dones espirituales, la resurrección y el amor como el camino más excelente.',
  47: '2 Corintios defiende el ministerio apostólico de Pablo, exhorta al arrepentimiento y alienta la generosidad en la ofrenda para los santos necesitados.',
  48: 'Gálatas defiende la justificación por la fe sola, no por obras de la Ley. Pablo confronta el legalismo y proclama la libertad en Cristo.',
  49: 'Efesios revela el plan eterno de Dios para unificar todas las cosas en Cristo, la salvación por gracia, la unidad de la iglesia y la vida práctica del creyente.',
  50: 'Filipenses es una carta de gozo escrita desde la prisión. Pablo anima a la unidad, la humildad (con el himno de Cristo) y el contentamiento en toda circunstancia.',
  51: 'Colosenses proclama la supremacía de Cristo sobre todo principado y potencia, advierte contra filosofías vacías y exhorta a vivir en Cristo en todas las áreas.',
  52: '1 Tesalonicenses agradece por la fe de los creyentes, los anima en la santidad y el trabajo, y enseña sobre la segunda venida de Cristo.',
  53: '2 Tesalonicenses corrige malentendidos sobre el Día del Señor, advierte contra la ociosidad y anima a perseverar en medio de la persecución.',
  54: '1 Timoteo instruye sobre el orden en la iglesia: requisitos para líderes, el papel de la mujer, la sana doctrina y la conducta del hombre de Dios.',
  55: '2 Timoteo es la última carta de Pablo desde la prisión, un llamado apasionado a la fidelidad en el ministerio, a predicar la Palabra y a soportar el sufrimiento por el evangelio.',
  56: 'Tito instruye sobre la organización de la iglesia en Creta, destacando la sana doctrina, las buenas obras y la gracia de Dios que enseña a vivir de manera recta.',
  57: 'Filemón es una carta personal donde Pablo intercede por Onésimo, un esclavo fugitivo, pidiendo a Filemón que lo reciba como hermano en Cristo.',
  58: 'Hebreos demuestra la superioridad de Cristo sobre los ángeles, Moisés y el sacerdocio levítico. Exhorta a la perseverancia en la fe, destacando a Cristo como el sumo sacerdote perfecto.',
  59: 'Santiago enfatiza la fe práctica: las pruebas producen paciencia, la fe sin obras está muerta, el control de la lengua y la sabiduría que viene de Dios.',
  60: '1 Pedro alienta a los creyentes que sufren persecución, recordándoles su esperanza viva, su identidad como pueblo santo y el ejemplo de Cristo en el sufrimiento.',
  61: '2 Pedro advierte contra los falsos maestros, llama al crecimiento espiritual y afirma la certeza de la segunda venida de Cristo.',
  62: '1 Juan asegura a los creyentes sobre su salvación, enfatiza el amor fraternal, la obediencia y la verdadera doctrina de Cristo, y advierte contra el anticristo.',
  63: '2 Juan advierte contra recibir a falsos maestros y exhorta a andar en la verdad y el amor.',
  64: '3 Juan elogia a Gayo por su hospitalidad, condena la falta de amor de Diótrefes y recomienda a Demetrio.',
  65: 'Judas advierte contra los falsos maestros que se han infiltrado en la iglesia, llamando a los creyentes a contender ardientemente por la fe.',
  66: 'Apocalipsis revela la victoria final de Cristo sobre el mal mediante visiones simbólicas. Incluye mensajes a las siete iglesias, juicios, la segunda venida y el nuevo cielo y tierra.',
};

const Map<int, int> bookChapterCounts = {
  1: 50,
  2: 40,
  3: 27,
  4: 36,
  5: 34,
  6: 24,
  7: 21,
  8: 4,
  9: 31,
  10: 24,
  11: 22,
  12: 25,
  13: 29,
  14: 36,
  15: 10,
  16: 13,
  17: 10,
  18: 42,
  19: 150,
  20: 31,
  21: 12,
  22: 8,
  23: 66,
  24: 52,
  25: 5,
  26: 48,
  27: 12,
  28: 14,
  29: 3,
  30: 9,
  31: 1,
  32: 4,
  33: 7,
  34: 3,
  35: 3,
  36: 3,
  37: 2,
  38: 14,
  39: 4,
  40: 28,
  41: 16,
  42: 24,
  43: 21,
  44: 28,
  45: 16,
  46: 16,
  47: 13,
  48: 6,
  49: 6,
  50: 4,
  51: 4,
  52: 5,
  53: 3,
  54: 6,
  55: 4,
  56: 3,
  57: 1,
  58: 13,
  59: 5,
  60: 5,
  61: 3,
  62: 5,
  63: 1,
  64: 1,
  65: 1,
  66: 22,
};
