class BookInfo {
  final int id;
  final String name;
  final String abbreviation;
  final String testament;
  final int position;

  const BookInfo({
    required this.id,
    required this.name,
    required this.abbreviation,
    required this.testament,
    required this.position,
  });
}

final List<BookInfo> bibleBooks = [
  // AT
  BookInfo(
    id: 1,
    name: 'Génesis',
    abbreviation: 'Gn',
    testament: 'old',
    position: 1,
  ),
  BookInfo(
    id: 2,
    name: 'Éxodo',
    abbreviation: 'Ex',
    testament: 'old',
    position: 2,
  ),
  BookInfo(
    id: 3,
    name: 'Levítico',
    abbreviation: 'Lv',
    testament: 'old',
    position: 3,
  ),
  BookInfo(
    id: 4,
    name: 'Números',
    abbreviation: 'Nm',
    testament: 'old',
    position: 4,
  ),
  BookInfo(
    id: 5,
    name: 'Deuteronomio',
    abbreviation: 'Dt',
    testament: 'old',
    position: 5,
  ),
  BookInfo(
    id: 6,
    name: 'Josué',
    abbreviation: 'Jos',
    testament: 'old',
    position: 6,
  ),
  BookInfo(
    id: 7,
    name: 'Jueces',
    abbreviation: 'Jue',
    testament: 'old',
    position: 7,
  ),
  BookInfo(
    id: 8,
    name: 'Rut',
    abbreviation: 'Rt',
    testament: 'old',
    position: 8,
  ),
  BookInfo(
    id: 9,
    name: '1 Samuel',
    abbreviation: '1 S',
    testament: 'old',
    position: 9,
  ),
  BookInfo(
    id: 10,
    name: '2 Samuel',
    abbreviation: '2 S',
    testament: 'old',
    position: 10,
  ),
  BookInfo(
    id: 11,
    name: '1 Reyes',
    abbreviation: '1 R',
    testament: 'old',
    position: 11,
  ),
  BookInfo(
    id: 12,
    name: '2 Reyes',
    abbreviation: '2 R',
    testament: 'old',
    position: 12,
  ),
  BookInfo(
    id: 13,
    name: '1 Crónicas',
    abbreviation: '1 Cr',
    testament: 'old',
    position: 13,
  ),
  BookInfo(
    id: 14,
    name: '2 Crónicas',
    abbreviation: '2 Cr',
    testament: 'old',
    position: 14,
  ),
  BookInfo(
    id: 15,
    name: 'Esdras',
    abbreviation: 'Esd',
    testament: 'old',
    position: 15,
  ),
  BookInfo(
    id: 16,
    name: 'Nehemías',
    abbreviation: 'Neh',
    testament: 'old',
    position: 16,
  ),
  BookInfo(
    id: 17,
    name: 'Ester',
    abbreviation: 'Est',
    testament: 'old',
    position: 17,
  ),
  BookInfo(
    id: 18,
    name: 'Job',
    abbreviation: 'Job',
    testament: 'old',
    position: 18,
  ),
  BookInfo(
    id: 19,
    name: 'Salmos',
    abbreviation: 'Sal',
    testament: 'old',
    position: 19,
  ),
  BookInfo(
    id: 20,
    name: 'Proverbios',
    abbreviation: 'Pr',
    testament: 'old',
    position: 20,
  ),
  BookInfo(
    id: 21,
    name: 'Eclesiastés',
    abbreviation: 'Ec',
    testament: 'old',
    position: 21,
  ),
  BookInfo(
    id: 22,
    name: 'Cantares',
    abbreviation: 'Cnt',
    testament: 'old',
    position: 22,
  ),
  BookInfo(
    id: 23,
    name: 'Isaías',
    abbreviation: 'Is',
    testament: 'old',
    position: 23,
  ),
  BookInfo(
    id: 24,
    name: 'Jeremías',
    abbreviation: 'Jer',
    testament: 'old',
    position: 24,
  ),
  BookInfo(
    id: 25,
    name: 'Lamentaciones',
    abbreviation: 'Lam',
    testament: 'old',
    position: 25,
  ),
  BookInfo(
    id: 26,
    name: 'Ezequiel',
    abbreviation: 'Ez',
    testament: 'old',
    position: 26,
  ),
  BookInfo(
    id: 27,
    name: 'Daniel',
    abbreviation: 'Dn',
    testament: 'old',
    position: 27,
  ),
  BookInfo(
    id: 28,
    name: 'Oseas',
    abbreviation: 'Os',
    testament: 'old',
    position: 28,
  ),
  BookInfo(
    id: 29,
    name: 'Joel',
    abbreviation: 'Jl',
    testament: 'old',
    position: 29,
  ),
  BookInfo(
    id: 30,
    name: 'Amós',
    abbreviation: 'Am',
    testament: 'old',
    position: 30,
  ),
  BookInfo(
    id: 31,
    name: 'Abdías',
    abbreviation: 'Abd',
    testament: 'old',
    position: 31,
  ),
  BookInfo(
    id: 32,
    name: 'Jonás',
    abbreviation: 'Jon',
    testament: 'old',
    position: 32,
  ),
  BookInfo(
    id: 33,
    name: 'Miqueas',
    abbreviation: 'Miq',
    testament: 'old',
    position: 33,
  ),
  BookInfo(
    id: 34,
    name: 'Nahúm',
    abbreviation: 'Nah',
    testament: 'old',
    position: 34,
  ),
  BookInfo(
    id: 35,
    name: 'Habacuc',
    abbreviation: 'Hab',
    testament: 'old',
    position: 35,
  ),
  BookInfo(
    id: 36,
    name: 'Sofonías',
    abbreviation: 'Sof',
    testament: 'old',
    position: 36,
  ),
  BookInfo(
    id: 37,
    name: 'Hageo',
    abbreviation: 'Hag',
    testament: 'old',
    position: 37,
  ),
  BookInfo(
    id: 38,
    name: 'Zacarías',
    abbreviation: 'Zac',
    testament: 'old',
    position: 38,
  ),
  BookInfo(
    id: 39,
    name: 'Malaquías',
    abbreviation: 'Mal',
    testament: 'old',
    position: 39,
  ),
  // NT
  BookInfo(
    id: 40,
    name: 'Mateo',
    abbreviation: 'Mt',
    testament: 'new',
    position: 1,
  ),
  BookInfo(
    id: 41,
    name: 'Marcos',
    abbreviation: 'Mc',
    testament: 'new',
    position: 2,
  ),
  BookInfo(
    id: 42,
    name: 'Lucas',
    abbreviation: 'Lc',
    testament: 'new',
    position: 3,
  ),
  BookInfo(
    id: 43,
    name: 'Juan',
    abbreviation: 'Jn',
    testament: 'new',
    position: 4,
  ),
  BookInfo(
    id: 44,
    name: 'Hechos',
    abbreviation: 'Hch',
    testament: 'new',
    position: 5,
  ),
  BookInfo(
    id: 45,
    name: 'Romanos',
    abbreviation: 'Ro',
    testament: 'new',
    position: 6,
  ),
  BookInfo(
    id: 46,
    name: '1 Corintios',
    abbreviation: '1 Co',
    testament: 'new',
    position: 7,
  ),
  BookInfo(
    id: 47,
    name: '2 Corintios',
    abbreviation: '2 Co',
    testament: 'new',
    position: 8,
  ),
  BookInfo(
    id: 48,
    name: 'Gálatas',
    abbreviation: 'Gá',
    testament: 'new',
    position: 9,
  ),
  BookInfo(
    id: 49,
    name: 'Efesios',
    abbreviation: 'Ef',
    testament: 'new',
    position: 10,
  ),
  BookInfo(
    id: 50,
    name: 'Filipenses',
    abbreviation: 'Flp',
    testament: 'new',
    position: 11,
  ),
  BookInfo(
    id: 51,
    name: 'Colosenses',
    abbreviation: 'Col',
    testament: 'new',
    position: 12,
  ),
  BookInfo(
    id: 52,
    name: '1 Tesalonicenses',
    abbreviation: '1 Ts',
    testament: 'new',
    position: 13,
  ),
  BookInfo(
    id: 53,
    name: '2 Tesalonicenses',
    abbreviation: '2 Ts',
    testament: 'new',
    position: 14,
  ),
  BookInfo(
    id: 54,
    name: '1 Timoteo',
    abbreviation: '1 Ti',
    testament: 'new',
    position: 15,
  ),
  BookInfo(
    id: 55,
    name: '2 Timoteo',
    abbreviation: '2 Ti',
    testament: 'new',
    position: 16,
  ),
  BookInfo(
    id: 56,
    name: 'Tito',
    abbreviation: 'Tit',
    testament: 'new',
    position: 17,
  ),
  BookInfo(
    id: 57,
    name: 'Filemón',
    abbreviation: 'Flm',
    testament: 'new',
    position: 18,
  ),
  BookInfo(
    id: 58,
    name: 'Hebreos',
    abbreviation: 'Heb',
    testament: 'new',
    position: 19,
  ),
  BookInfo(
    id: 59,
    name: 'Santiago',
    abbreviation: 'Stg',
    testament: 'new',
    position: 20,
  ),
  BookInfo(
    id: 60,
    name: '1 Pedro',
    abbreviation: '1 P',
    testament: 'new',
    position: 21,
  ),
  BookInfo(
    id: 61,
    name: '2 Pedro',
    abbreviation: '2 P',
    testament: 'new',
    position: 22,
  ),
  BookInfo(
    id: 62,
    name: '1 Juan',
    abbreviation: '1 Jn',
    testament: 'new',
    position: 23,
  ),
  BookInfo(
    id: 63,
    name: '2 Juan',
    abbreviation: '2 Jn',
    testament: 'new',
    position: 24,
  ),
  BookInfo(
    id: 64,
    name: '3 Juan',
    abbreviation: '3 Jn',
    testament: 'new',
    position: 25,
  ),
  BookInfo(
    id: 65,
    name: 'Judas',
    abbreviation: 'Jud',
    testament: 'new',
    position: 26,
  ),
  BookInfo(
    id: 66,
    name: 'Apocalipsis',
    abbreviation: 'Ap',
    testament: 'new',
    position: 27,
  ),
];

final Map<int, BookInfo> booksById = {for (final b in bibleBooks) b.id: b};
final Map<String, BookInfo> booksByName = {
  for (final b in bibleBooks) b.name.toLowerCase(): b,
};
final Map<String, BookInfo> booksByAbbr = {
  for (final b in bibleBooks) b.abbreviation.toLowerCase(): b,
};

final Map<int, String> bookSummaries = {
  1: 'Autor: Moisés. Fecha: ~1446-1406 a.C.\n\nGénesis es el libro de los comienzos. Describe la creación del universo en seis días, la creación del hombre y la mujer, la entrada del pecado al mundo (Génesis 3), el primer asesinato, el diluvio universal y la torre de Babel. A partir del capítulo 12, se enfoca en Abraham, el padre de la fe, con quien Dios establece un pacto eterno. Continúa con Isaac, Jacob (cuyo nombre cambia a Israel) y sus doce hijos, especialmente José, cuya historia de sufrimiento y exaltación ocupa los capítulos 37-50. Establece las bases de todas las doctrinas fundamentales y la promesa del Mesías que bendeciría a todas las naciones.',
  2: 'Autor: Moisés. Fecha: ~1446-1406 a.C.\n\nÉxodo narra la esclavitud de Israel en Egipto, el nacimiento y llamamiento de Moisés, las diez plagas sobre Egipto (agua en sangre, ranas, piojos, moscas, pestilencia, úlceras, granizo, langostas, tinieblas, muerte de los primogénitos), la institución de la Pascua (capítulo 12), el cruce milagroso del Mar Rojo y la liberación de la esclavitud. La segunda mitad del libro (capítulos 19-40) se desarrolla en el Monte Sinaí, donde Dios entrega los Diez Mandamientos y las leyes del pacto. Incluye las instrucciones detalladas para construir el Tabernáculo, el lugar donde la presencia de Dios habitaba en medio del pueblo.',
  3: 'Autor: Moisés. Fecha: ~1446-1406 a.C.\n\nLevítico es el manual de santidad y adoración. Contiene las leyes sobre los cinco tipos de sacrificios (holocausto, ofrenda, paz, expiación, reparación), la consagración de los sacerdotes (Aarón y sus hijos), las leyes de pureza e impureza (alimentos, enfermedades de la piel, flujos corporales), el Día de la Expiación (Yom Kipur, capítulo 16), las leyes de santidad para el pueblo (capítulos 17-22) y el calendario de fiestas solemnes (Pascua, Pentecostés, Tabernáculos). Su tema central es: "Sed santos, porque yo soy santo".',
  4: 'Autor: Moisés. Fecha: ~1446-1406 a.C.\n\nNúmeros describe los 40 años de peregrinación de Israel por el desierto. Comienza con el censo de las tribus (capítulos 1-4) y la organización del campamento alrededor del Tabernáculo. Incluye las rebeliones del pueblo (por comida, contra Moisés, la rebelión de Coré), la negativa a entrar a Canaán por miedo a los gigantes, la serpiente de bronce (capítulo 21), el profetismo de Balaam, y concluye con el segundo censo y la preparación para entrar a la Tierra Prometida. Destaca la fidelidad de Dios a pesar de la constante incredulidad del pueblo.',
  5: 'Autor: Moisés. Fecha: ~1406 a.C.\n\nDeuteronomio significa "segunda ley". Son tres discursos de Moisés pronunciados en las llanuras de Moab antes de morir, dirigidos a la nueva generación que entraría a Canaán. Moisés repasa la historia del Éxodo (capítulos 1-4), recita los Diez Mandamientos (capítulo 5), expone las leyes detalladas para la vida en la tierra prometida (capítulos 12-26), y presenta las bendiciones por obediencia y maldiciones por desobediencia (capítulo 28). Incluye el gran mandamiento: "Amarás al Señor tu Dios con todo tu corazón" (Deuteronomio 6:4-5). Moisés muere en el Monte Nebo después de ver la tierra desde lejos.',
  6: 'Autor: Josué (tradicionalmente). Fecha: ~1406-1380 a.C.\n\nJosué narra la conquista de Canaán bajo el liderazgo de Josué, sucesor de Moisés. Incluye el cruce milagroso del río Jordán (capítulo 3), la caída de Jericó (capítulo 6), el pecado de Acán y la derrota en Hai (capítulo 7), las campañas militares contra los reyes del sur y del norte, y la distribución de la tierra entre las doce tribus (capítulos 13-22). Termina con el discurso de despedida de Josué, quien desafía al pueblo a servir a Dios: "Escogeos hoy a quién sirváis... pero yo y mi casa serviremos al Señor" (Josué 24:15).',
  7: 'Autor: Tradicionalmente Samuel (desconocido). Fecha: ~1050-1000 a.C.\n\nJueces cubre un período de aproximadamente 300 años entre la conquista de Canaán y el establecimiento de la monarquía. Sigue un ciclo repetitivo: Israel peca, Dios los entrega a un opresor, el pueblo clama, Dios levanta un juez que los libera, hay paz, y luego el ciclo se repite al morir el juez. Los jueces principales incluyen: Débora (la única mujer, capítulos 4-5), Gedeón (capítulos 6-8), Jefté (capítulos 10-12) y Sansón (capítulos 13-16). La frase repetida es: "Cada uno hacía lo que bien le parecía" (Jueces 21:25).',
  8: 'Autor: Tradicionalmente Samuel (desconocido). Fecha: ~1000 a.C.\n\nRut es una novela corta ubicada en el período de los jueces. Cuenta la historia de Noemí, una viuda que regresa a Belén desde Moab, acompañada por su nuera Rut, una moabita que le jura lealtad eterna (Rut 1:16-17). Rut recoge espigas en el campo de Booz, un pariente rico que resulta ser el redentor. Booz se casa con Rut, redimiendo la tierra y el nombre de la familia. La historia culmina con el nacimiento de Obed, abuelo del rey David, insertando a Rut en la genealogía del Mesías. Es un hermoso ejemplo de lealtad, bondad y providencia divina.',
  9: 'Autor: Probablemente Samuel, Natán y Gad (compilado por profetas). Fecha: ~930 a.C.\n\n1 Samuel cubre la transición de Israel de una teocracia a una monarquía. Comienza con el nacimiento milagroso de Samuel (capítulos 1-3), el último juez y primer profeta. El pueblo pide un rey, y Dios les da a Saúl (capítulo 8-10). Saúl comienza bien pero desobedece a Dios repetidamente, siendo rechazado como rey. David es ungido por Samuel (capítulo 16), derrota a Goliat (capítulo 17), y desarrolla una amistad profunda con Jonatán. Saúl persigue a David por celos durante años. El libro termina con la muerte de Saúl y Jonatán en batalla (capítulo 31).',
  10: 'Autor: Probablemente Natán y Gad. Fecha: ~930 a.C.\n\n2 Samuel sigue el reinado de David sobre Judá primero (7 años) y luego sobre todo Israel (33 años). David conquista Jerusalén, la establece como capital y traslada el arca del pacto. Dios hace un pacto eterno con David (capítulo 7): su trono permanecería para siempre (cumplido en Cristo). David comete adulterio con Betsabé y asesina a Urías (capítulo 11), su pecado más grave. El profeta Natán lo confronta (capítulo 12). Las consecuencias son devastadoras: la muerte del hijo de Betsabé, la violación de Tamar, el asesinato de Amnón, y la rebelión de Absalón que obliga a David a huir de Jerusalén. David regresa pero el reino queda debilitado.',
  11: 'Autor: Probablemente Jeremías (tradición judía). Fecha: ~560-540 a.C.\n\n1 Reyes comienza con David anciano y la sucesión de Salomón (capítulos 1-2). Salomón pide sabiduría a Dios (capítulo 3), construye el Templo de Jerusalén (capítulos 5-8), y su reino alcanza una gloria sin precedentes, pero su corazón se desvía por sus muchas esposas extranjeras (capítulo 11). Después de su muerte, el reino se divide: 10 tribus al norte (Israel) con Jeroboam, y 2 tribus al sur (Judá) con Roboam (capítulo 12). El libro alterna entre los reyes del norte y del sur, destacando al profeta Elías, quien desafía a los profetas de Baal en el Monte Carmelo (capítulo 18) y huye a Horeb donde escucha la voz de Dios en un silbo apacible.',
  12: 'Autor: Probablemente Jeremías (tradición judía). Fecha: ~560-540 a.C.\n\n2 Reyes continúa la historia de los dos reinos. En el reino del norte (Israel), Elías es llevado al cielo, y Eliseo realiza muchos milagros (purificación del agua, multiplicación del aceite, resurrección del hijo de la sunamita, sanación de Naamán). Finalmente, en el año 722 a.C., Asiria conquista Samaria y el reino del norte es llevado al exilio por su persistente idolatría (capítulo 17). En el reino del sur (Judá), destacan reyes reformadores como Ezequías (capítulos 18-20) y Josías (capítulos 22-23), pero el pecado del pueblo lleva al juicio. Nabucodonosor conquista Jerusalén en 586 a.C., destruye el Templo y lleva a Judá al exilio babilónico (capítulo 25).',
  13: 'Autor: Esdras (tradición). Fecha: ~450-430 a.C.\n\n1 Crónicas comienza con extensas genealogías desde Adán hasta David (capítulos 1-9), estableciendo el linaje de las tribus de Israel, especialmente la tribu de Judá y la familia sacerdotal de Leví. Luego se enfoca exclusivamente en el reinado de David (capítulos 10-29), omitiendo sus pecados y conflictos para presentarlo como el rey ideal. David trae el arca a Jerusalén, recibe el pacto davídico de Dios, organiza a los levitas y sacerdotes para el servicio del Templo, y hace preparativos exhaustivos para la construcción del Templo que su hijo Salomón edificaría. El libro enfatiza la adoración y el propósituo de Dios para su pueblo.',
  14: 'Autor: Esdras (tradición). Fecha: ~450-430 a.C.\n\n2 Crónicas cubre desde el reinado de Salomón hasta el exilio babilónico. Describe en detalle la construcción y dedicación del Templo (capítulos 2-7), la visita de la reina de Saba, y las riquezas de Salomón. Luego narra la historia de los reyes de Judá (excluyendo al reino del norte), destacando a aquellos que siguieron a Dios: Asa, Josafat, Joás, Ezequías (quien purifica el Templo y celebra la Pascua) y Josías (quien encuentra el libro de la Ley y realiza una gran reforma). Concluye con la destrucción de Jerusalén y el decreto de Ciro que permite el regreso de los exiliados (2 Crónicas 36). El énfasis está en la relación entre la obediencia y la bendición de Dios.',
  15: 'Autor: Esdras. Fecha: ~450 a.C.\n\nEsdras narra el regreso de los judíos del exilio en Babilonia en dos oleadas. La primera (capítulos 1-6), liderada por Zorobabel y Josué, reconstruye el altar y los cimientos del Templo, enfrenta oposición de los samaritanos, y finalmente completa el Templo en 516 a.C. (unos 70 años después de su destrucción). La segunda oleada (capítulos 7-10), liderada por Esdras, un escriba experto en la Ley de Moisés, llega a Jerusalén 60 años después. Esdras descubre que el pueblo se ha casado con mujeres extranjeras, lo que viola la Ley. Lidera un movimiento de arrepentimiento nacional y restauración de la pureza del pacto.',
  16: 'Autor: Nehemías (basado en sus memorias). Fecha: ~445-430 a.C.\n\nNehemías, copero del rey Artajerjes de Persia, recibe permiso para reconstruir los muros de Jerusalén. A pesar de la feroz oposición de Sanbalat, Tobías y Gesem, el pueblo trabaja hombro a hombro y completa los muros en solo 52 días (capítulo 6). Luego, Nehemías y Esdras lideran una gran asamblea donde se lee la Ley públicamente, el pueblo confiesa sus pecados y renueva el pacto con Dios (capítulos 8-10). Nehemías regresa a Persia y luego vuelve a Jerusalén para enfrentar problemas renovados: abusos en el Templo, violación del sábado y matrimonios mixtos. El libro muestra un liderazgo piadoso que combina oración, planificación práctica y valentía.',
  17: 'Autor: Tradicionalmente Mardoqueo o Esdras (desconocido). Fecha: ~465-460 a.C.\n\nEster es único porque Dios nunca es mencionado explícitamente, aunque su providencia se ve en cada evento. Ambientado en Susa, capital del imperio Persa, el rey Asuero (Jerjes) repudia a la reina Vasti y escoge a Ester, una joven judía, como nueva reina. Amán, el alto oficial del rey, planea exterminar a todos los judíos por su odio hacia Mardoqueo (tío de Ester). Mardoqueo insta a Ester a interceder ante el rey con la famosa frase: "¿Y quién sabe si para esto has llegado al reino?" (Ester 4:14). Ester arriesga su vida, revela su identidad judía y expone el complot. Amán es ahorcado en la horca que había preparado para Mardoqueo, y los judíos son salvados. La fiesta de Purim conmemora esta liberación.',
  18: 'Autor: Tradicionalmente Moisés o un sabio (desconocido). Fecha: ~2000-500 a.C. (incierta)\n\nJob es una obra maestra de la literatura sapiencial que aborda el problema del sufrimiento inocente. Job es descrito como "perfecto y recto", temeroso de Dios. Satanás lo acusa de servir a Dios solo por bendición, y Dios permite que Job sea probado extremadamente: pierde sus hijos, sus riquezas y su salud. Tres amigos (Elifaz, Bildad y Zofar) vienen a consolarlo pero terminan acusándolo de pecado oculto. Job protesta su inocencia y exige una respuesta de Dios (capítulos 3-31). Un joven llamado Eliú habla (capítulos 32-37), y finalmente Dios responde desde un torbellino (capítulos 38-41), revelando su soberanía y sabiduría inescrutable en la creación. Job se arrepiente en polvo y ceniza, y Dios restaura su fortuna al doble. Versículo clave: "Yo sé que mi Redentor vive" (Job 19:25).',
  19: 'Autor: Principalmente David, también Asaf, los hijos de Coré, Moisés, Salomón, Hemán, Etán y otros. Fecha: ~1440-450 a.C.\n\nSalmos es el himnario de Israel: 150 poemas y canciones que cubren toda la gama de la experiencia humana y espiritual. Se divide en cinco libros: Libro I (1-41), Libro II (42-72), Libro III (73-89), Libro IV (90-106), Libro V (107-150). Incluye salmos mesiánicos (2, 22, 110), salmos de lamento (13, 22, 42, 137), salmos de acción de gracias (18, 30, 100, 136), salmos de alabanza (8, 19, 29, 95-100, 148-150), salmos de sabiduría (1, 19, 119), y salmos de confianza (23, 27, 46, 91, 121). El Salmo 119, el más largo (176 versículos), es una meditación sobre la Palabra de Dios. Jesús citó los Salmos con frecuencia, especialmente el Salmo 22 en la cruz.',
  20: 'Autor: Principalmente Salomón, también Agur y Lemuel. Fecha: ~970-700 a.C.\n\nProverbios es una colección de dichos sabios que enseñan cómo vivir con sabiduría en el temor de Dios. Los primeros 9 capítulos son discursos de un padre a su hijo, personificando la Sabiduría como una mujer que clama en las calles. Los capítulos 10-29 contienen proverbios cortos y paralelos sobre temas como: la disciplina, el trabajo diligente vs. la pereza, el poder de las palabras, la honestidad, el orgullo vs. la humildad, la ira, la amistad, el matrimonio, la crianza de los hijos, la justicia, la pobreza y la riqueza, y el temor del Señor como principio de la sabiduría. El capítulo 31 describe a la mujer virtuosa. Versículo clave: "El principio de la sabiduría es el temor del Señor" (Proverbios 9:10).',
  21: 'Autor: Salomón (tradicionalmente). Fecha: ~970-930 a.C.\n\nEclesiastés es la reflexión de un anciano sabio (el Predicador) que ha buscado significado en todo lo que el mundo ofrece: el placer, el trabajo, la sabiduría, las riquezas, el poder, y concluye que "todo es vanidad y aflicción de espíritu". El libro enfrenta honestamente las preguntas difíciles de la vida: ¿Qué sentido tiene trabajar si al final morimos? ¿Qué valor tiene la sabiduría si el sabio muere como el necio? ¿Hay justicia en el mundo? El Predicador concluye que la vida es un don de Dios para disfrutar con temor de Dios, y que Dios juzgará todo en su tiempo. Versículo clave: "El fin de todo el discurso es este: Teme a Dios y guarda sus mandamientos, porque esto es el todo del hombre" (Eclesiastés 12:13).',
  22: 'Autor: Salomón (tradicionalmente). Fecha: ~970-930 a.C.\n\nCantares (Cantar de los Cantares) es un poema de amor nupcial entre el rey Salomón y la sulamita (su amada). Es un diálogo poético lleno de metáforas orientales que celebran la belleza, el deseo y la intimidad del amor conyugal como un regalo de Dios. La estructura es dramática, con intercambios entre el Esposo, la Esposa y el Coro. Ha sido interpretado alegóricamente como el amor entre Dios e Israel, o entre Cristo y la Iglesia. Versículo clave: "Fuerte como la muerte es el amor" (Cantares 8:6). Es una afirmación de la bondad del amor sexual dentro del matrimonio.',
  23: 'Autor: Isaías (hijo de Amoz). Fecha: ~740-680 a.C.\n\nIsaías es el libro profético más extenso (66 capítulos) y uno de los más importantes del AT. Primera parte (capítulos 1-39): Isaías profetiza durante los reinados de Uzías, Jotam, Acaz y Ezequías en Judá. Anuncia juicio contra Judá y Jerusalén por su pecado e idolatría, pero también ofrece esperanza: "He aquí, la virgen concebirá y dará a luz un hijo, y llamará su nombre Emmanuel" (Isaías 7:14). Incluye la visión del trono de Dios (capítulo 6), la profecía del Renuevo (capítulo 11, el gobierno del Mesías) y juicios contra las naciones. Segunda parte (capítulos 40-66): Anuncia consuelo y restauración después del exilio. Contiene los cuatro "Cánticos del Siervo Sufriente" (42, 49, 50, 52-53), que describen al Mesías que muere por los pecados del pueblo: "Mas él fue herido por nuestras transgresiones, molido por nuestras iniquidades" (Isaías 53:5). Termina con la promesa de "cielos nuevos y tierra nueva" (Isaías 65-66).',
  24: 'Autor: Jeremías (con ayuda de Baruc su escriba). Fecha: ~626-586 a.C.\n\nJeremías, conocido como "el profeta llorón", profetizó durante 40 años (desde Josías hasta la caída de Jerusalén) llamando a Judá al arrepentimiento. Advirtió repetidamente que Babilonia conquistaría Jerusalén si no se arrepentían. Fue perseguido, encarcelado, metido en un pozo de lodo, y rechazado por su propio pueblo. Incluye el sermón del Templo (capítulo 7), la lección del alfarero y el barro (capítulo 18), la profecía de los 70 años de cautiverio (capítulo 25), la carta a los exiliados (capítulo 29), la promesa del Nuevo Pacto escrito en los corazones (Jeremías 31:31-34), y la compra del campo como señal de restauración (capítulo 32). Después de la caída de Jerusalén, Jeremías fue llevado a Egipto contra su voluntad (capítulo 43).',
  25: 'Autor: Jeremías (tradicionalmente). Fecha: ~586 a.C.\n\nLamentaciones consta de cinco poemas acrósticos (cada versículo comienza con una letra del alfabeto hebreo en orden) que lloran la destrucción de Jerusalén por Babilonia en 586 a.C. Describe el horror del asedio: el hambre tan extrema que las madres cocinan a sus hijos (Lamentaciones 2:20, 4:10), la destrucción del Templo, el rey cautivo, y la desolación de la ciudad santa. Sin embargo, en medio del lamento más oscuro hay un rayo de esperanza: "Por la misericordia del Señor no hemos sido consumidos, porque nunca decayeron sus misericordias. Nuevas son cada mañana; grande es tu fidelidad" (Lamentaciones 3:22-23). El libro termina con una oración pidiendo restauración.',
  26: 'Autor: Ezequiel (sacerdote y profeta). Fecha: ~593-570 a.C.\n\nEzequiel profetizó entre los exiliados en Babilonia durante 22 años. Comienza con una impresionante visión de la gloria de Dios en un carro-trono con cuatro seres vivientes (capítulo 1). Es llamado a ser centinela de Israel (capítulo 3). Anuncia el juicio inminente sobre Jerusalén mediante acciones simbólicas (capítulos 4-24). Luego profetiza contra siete naciones (capítulos 25-32). La segunda mitad (capítulos 33-48) ofrece esperanza de restauración: la visión de los huesos secos que reviven (capítulo 37, símbolo de la restauración nacional y espiritual de Israel), la profecía contra Gog y Magog (capítulos 38-39), la visión del nuevo Templo (capítulos 40-44), el río que fluye del Templo (capítulo 47) y la distribución de la tierra restaurada (capítulo 48). Tema clave: "Sabrán que yo soy el Señor".',
  27: 'Autor: Daniel. Fecha: ~605-536 a.C.\n\nDaniel fue llevado cautivo a Babilonia como joven noble y sirvió en la corte real durante los imperios babilónico y persa. La primera parte (capítulos 1-6) narra historias: Daniel y sus amigos (Sadrac, Mesac y Abed-nego) se mantienen fieles a Dios en la corte (capítulo 1), Nabucodonosor sueña con una gran estatua (capítulo 2), los amigos son salvados del horno de fuego (capítulo 3), la locura de Nabucodonosor (capítulo 4), la escritura en la pared (capítulo 5) y Daniel en el foso de los leones (capítulo 6). La segunda parte (capítulos 7-12) contiene visiones apocalípticas: las cuatro bestias, el carnero y el macho cabrío, la profecía de las 70 semanas (capítulo 9, una de las profecías mesiánicas más importantes), y visiones detalladas del conflicto entre el reino de Dios y los reinos del mundo.',
  28: 'Autor: Oseas. Fecha: ~755-715 a.C.\n\nOseas profetizó al reino del norte (Israel) durante sus últimos años antes de la conquista asiria. Dios le ordena casarse con Gomer, una mujer infiel, como símbolo viviente del matrimonio de Dios con Israel, que le ha sido infiel adorando a otros dioses (idolatría = adulterio espiritual). Oseas y Gomer tienen tres hijos: Jezreel, Lo-ruhama (No compadecida) y Lo-ammi (No pueblo mío). Después de que Gomer lo abandona y termina esclavizada, Oseas la redime, mostrando el amor persistente de Dios. El libro alterna entre oráculos de juicio y promesas de restauración. Versículo clave: "Porque misericordia quiero, y no sacrificio, y conocimiento de Dios más que holocaustos" (Oseas 6:6). Termina con un llamado al arrepentimiento y la promesa de sanidad.',
  29: 'Autor: Joel (hijo de Petuel). Fecha: ~835-796 a.C. o ~500 a.C. (incierta)\n\nJoel comienza describiendo una devastadora plaga de langostas como un ejército invasor, que interpreta como el juicio de Dios y una advertencia del "Día del Señor". Llama al pueblo al arrepentimiento genuino: "Rasgad vuestro corazón, y no vuestros vestidos" (Joel 2:13). Dios promete restauración: la plaga será quitada y la tierra será fértil de nuevo. El punto culminante es la profecía del derramamiento del Espíritu Santo sobre toda carne (Joel 2:28-32), que Pedro citó en Pentecostés (Hechos 2:17-21). También anuncia juicio sobre las naciones y bendición final para Judá y Jerusalén.',
  30: 'Autor: Amós (pastor y recogedor de higos). Fecha: ~760-750 a.C.\n\nAmós, un pastor de Tecoa (Judá), fue enviado por Dios a profetizar al reino del norte (Israel) durante el próspero reinado de Jeroboam II. Denuncia la injusticia social: los ricos oprimen a los pobres, venden al justo por dinero, viven en lujo mientras hay necesidad. Declara que el verdadero culto a Dios no puede separarse de la justicia social: "Corra el juicio como las aguas, y la justicia como impetuoso arroyo" (Amós 5:24). Anuncia el juicio inminente de Israel por sus pecados, pero termina con una promesa de restauración del tabernáculo caído de David (Amós 9:11-15). Es un poderoso llamado a la integridad personal y social.',
  31: 'Autor: Abdías. Fecha: ~586 a.C. (después de la caída de Jerusalén)\n\nAbdías es el libro más corto del AT (solo 21 versículos). Profetiza el juicio contra Edom, nación descendiente de Esaú, por su violencia contra Judá. Cuando Jerusalén fue saqueada por Babilonia, los edomitas no solo no ayudaron a sus hermanos sino que se alegraron de su desgracia, saquearon la ciudad y entregaron a los fugitivos (versículos 10-14). Abdías anuncia que Edom será destruido y humillado, mientras que el monte de Sión (Israel) será restaurado. "Y será el reino del Señor" (versículo 21). El principio: el orgullo precede a la caída, y Dios es juez de todas las naciones.',
  32: 'Autor: Tradicionalmente el profeta Jonás (hijo de Amitai). Fecha: ~780-750 a.C.\n\nJonás es diferente a los otros profetas: no es una colección de oráculos sino una historia. Dios llama a Jonás a predicar contra Nínive (capital de Asiria, enemigo de Israel), pero Jonás huye en dirección opuesta hacia Tarsis. Después de una tormenta, los marineros lo lanzan al mar, y un gran pez lo traga. Dentro del pez, Jonás se arrepiente y ora (capítulo 2). El pez lo vomita, y Jonás obedece predicando a Nínive. Sorpresivamente, toda la ciudad se arrepiente (capítulo 3). Jonás se enoja porque Dios es misericordioso con los enemigos de Israel. Dios le enseña mediante una calabacera que su amor se extiende a todas las naciones (capítulo 4). El libro muestra que Dios se preocupa por todos los pueblos.',
  33: 'Autor: Miqueas (de Moréset). Fecha: ~735-700 a.C.\n\nMiqueas profetizó a Judá e Israel durante los reinados de Jotam, Acaz y Ezequías. Denuncia la corrupción de los líderes, los falsos profetas, la injusticia social y la idolatría. Anuncia el juicio: Samaria será destruida y Jerusalén será arrasada. Pero también contiene algunas de las profecías mesiánicas más hermosas: el nacimiento del gobernante en Belén (Miqueas 5:2, citado por los magos en Mateo 2), y un reino de paz donde "forjarán sus espadas en rejas de arado" (Miqueas 4:3). El resumen de lo que Dios requiere: "Hacer justicia, amar misericordia, y humillarte ante tu Dios" (Miqueas 6:8). Termina con una oración de confianza en el perdón y la misericordia de Dios.',
  34: 'Autor: Nahúm (de Elcós). Fecha: ~663-612 a.C.\n\nNahúm profetiza la caída de Nínive (capital de Asiria), aproximadamente 100 años después del arrepentimiento bajo la predicación de Jonás. Asiria había vuelto a su maldad y era conocida por su extrema crueldad. Nahúm describe el juicio de Dios contra Nínive con un lenguaje poético poderoso: será destruida por inundación, sus líderes huirán, sus riquezas serán saqueadas. El libro consuela a Judá con la promesa de que Dios es "tardo para la ira y grande en poder" (Nahúm 1:3), y que el opresor será derrotado. La destrucción de Nínive en 612 a.C. cumplió esta profecía. Hermoso versículo: "¡Cuán hermosos son sobre los montes los pies del que trae buenas nuevas!" (Nahúm 1:15).',
  35: 'Autor: Habacuc. Fecha: ~608-598 a.C.\n\nHabacuc es único porque es un diálogo entre el profeta y Dios. Habacuc cuestiona a Dios: "¿Por qué permites la violencia y la injusticia?" (capítulo 1). Dios responde que levantará a los caldeos (Babilonia) para ejecutar juicio. Habacuc queda perplejo: "¿Cómo puede un Dios santo usar una nación más malvada que Judá?" (capítulo 1:12-17). Dios responde que los justos vivirán por su fe (Habacuc 2:4, citado tres veces en el NT), y que el orgulloso caerá. El capítulo 2 contiene las cinco "ayes" contra Babilonia. El capítulo 3 es una oración-poema que describe una teofanía poderosa, y termina con una de las declaraciones de fe más sublimes: "Aunque la higuera no florezca... con todo, yo me alegraré en el Señor" (Habacuc 3:17-18).',
  36: 'Autor: Sofonías. Fecha: ~640-609 a.C.\n\nSofonías profetizó durante el reinado de Josías, antes de la reforma religiosa. Anuncia el "Día del Señor" como un día de juicio terrible contra Judá por su idolatría, violencia y complacencia. Pero también declara juicio contra las naciones vecinas: Filistia, Moab, Amón, Etiopía y Asiria. Sin embargo, el libro termina con promesas de restauración: un remanente humilde y justo será salvo, Dios se regocijará sobre Jerusalén con cánticos, y reunirá a su pueblo disperso. Versículo clave: "Jehová tu Dios está en medio de ti, poderoso, él salvará; se gozará sobre ti con alegría, callará de amor, se regocijará sobre ti con cánticos" (Sofonías 3:17).',
  37: 'Autor: Hageo. Fecha: ~520 a.C.\n\nHageo profetizó después del exilio, cuando los judíos habían regresado a Jerusalén pero habían dejado de reconstruir el Templo, ocupándose de sus propias casas mientras la casa de Dios estaba en ruinas. En cuatro mensajes breves (cubriendo unos 4 meses), Hageo confronta al pueblo: "¿Es tiempo de que habitéis en casas artesonadas, mientras esta casa está desierta?" (Hageo 1:4). Llama a reanudar la construcción del Templo, prometiendo que la gloria posterior será mayor que la primera, y que Dios traerá paz. Zorobabel (gobernador) y Josué (sumo sacerdote) responden, y la construcción se reanuda. Hageo señala que poner a Dios en primer lugar trae bendición.',
  38: 'Autor: Zacarías (hijo de Berequías). Fecha: ~520-518 a.C.\n\nZacarías profetizó junto con Hageo, animando al pueblo a reconstruir el Templo. Contiene ocho visiones simbólicas en una noche (capítulos 1-6): el jinete entre los mirtos, los cuatro cuernos y cuatro carpinteros, el hombre con el cordel de medir, Josué el sumo sacerdote, el candelabro de oro y los dos olivos, el rollo volador, la mujer en el efa, y los cuatro carros. Luego, Zacarías da mensajes sobre la importancia de la justicia y la misericordia (capítulos 7-8). Los capítulos 9-14 contienen profecías mesiánicas detalladas: la entrada triunfal del Rey en Jerusalén montado en un asno (Zacarías 9:9), el precio de treinta piezas de plata (Zacarías 11:12-13), el traspasado (Zacarías 12:10), la fuente abierta para el pecado (Zacarías 13:1), y el día del Señor cuando sus pies estarán sobre el Monte de los Olivos (Zacarías 14:4).',
  39: 'Autor: Malaquías. Fecha: ~433-430 a.C.\n\nMalaquías, el último profeta del AT, confronta la apatía espiritual y la corrupción en Judá después del exilio. Usa un estilo de diálogo: Dios acusa, el pueblo responde "¿En qué?", y Dios detalla. Denuncia: los sacerdotes ofrecen sacrificios defectuosos (capítulo 1), el pueblo es infiel en los diezmos (capítulo 3), se casan con mujeres extranjeras y se divorcian (capítulo 2). Anuncia la venida del mensajero que preparará el camino (Juan el Bautista, capítulo 3:1) y el Sol de Justicia que traerá sanidad (capítulo 4:2). Termina con la profecía de Elías antes del gran día del Señor (Malaquías 4:5-6).El AT cierra con esta nota de esperanza y advertencia, preparando el camino para el Nuevo Testamento.',
  40: 'Autor: Mateo (Leví, el publicano/apóstol). Fecha: ~50-60 d.C.\n\nMateo es el evangelio del Rey y el cumplimiento profético. Presenta a Jesús como el Mesías prometido, el Hijo de David y el cumplimiento de las profecías del AT (usando más de 60 veces la frase "para que se cumpliese"). Comienza con la genealogía de Jesús (capítulo 1), su nacimiento virginal y la visita de los magos. Incluye los grandes bloques de enseñanza: el Sermón del Monte (capítulos 5-7, las Bienaventuranzas), las parábolas del Reino (capítulo 13), y el discurso del Monte de los Olivos (capítulos 24-25). Destaca la confesión de Pedro, la transfiguración, la institución de la Cena del Señor, la crucifixión y la resurrección. Termina con la Gran Comisión (Mateo 28:18-20): "Id y haced discípulos a todas las naciones".',
  41: 'Autor: Juan Marcos (compañero de Pedro). Fecha: ~55-65 d.C.\n\nMarcos es el evangelio más corto y dinámico, probablemente escrito primero. Presenta a Jesús como el Siervo de Dios en acción continua, con un ritmo acelerado usando la palabra "inmediatamente" más de 40 veces. Comienza directamente con el ministerio de Juan el Bautista y el bautismo de Jesús. Enfatiza los milagros de Jesús (endemoniados, sanidades, alimentación de 5000, caminar sobre el agua) más que sus discursos. Destaca el sufrimiento del Hijo del Hombre (capítulo 8:31, 9:31, 10:33-34). Pedro es una figura central. El libro termina abruptamente (Marcos 16:8), con las mujeres huyendo del sepulcro vacío. Los versículos 9-20 fueron añadidos posteriormente. Es un llamado al discipulado: tomar la cruz y seguir a Jesús.',
  42: 'Autor: Lucas (médico y compañero de Pablo). Fecha: ~58-62 d.C.\n\nLucas es el evangelio más detallado y completo, escrito por un médico griego a Teófilo. Presenta a Jesús como el Salvador de toda la humanidad. Incluye los relatos más detallados del nacimiento de Jesús (capítulos 1-2): el anuncio a Zacarías, la Anunciación a María, el Magníficat, el nacimiento en Belén, los pastores, la presentación en el Templo, Jesús en el Templo a los 12 años. Destaca la compasión de Jesús por los marginados: mujeres, pobres, samaritanos, publicanos, pecadores. Contiene parábolas únicas: el buen samaritano (capítulo 10), el hijo pródigo (capítulo 15), el rico y Lázaro (capítulo 16), y el fariseo y el publicano (capítulo 18). Enfatiza la oración y el Espíritu Santo. La resurrección incluye el camino a Emaús (capítulo 24).',
  43: 'Autor: Juan (el apóstol, hijo de Zebedeo). Fecha: ~85-95 d.C.\n\nJuan es el evangelio más teológico y profundo. Presenta a Jesús como el Hijo de Dios, el Verbo (Logos) eterno que se hizo carne (Juan 1:1-14). Contiene siete señales milagrosas (agua en vino, sanidad del hijo del oficial, sanidad del paralítico, alimentación de 5000, caminar sobre el agua, sanidad del ciego de nacimiento, resurrección de Lázaro) que demuestran su divinidad. Incluye los "Yo Soy" de Jesús: Pan de Vida, Luz del Mundo, Puerta, Buen Pastor, Resurrección y Vida, Camino-Verdad-Vida, Vid Verdadera. Contiene discursos profundos: el nuevo nacimiento (capítulo 3), el agua viva (capítulo 4), el Pan de Vida (capítulo 6), el discurso del aposento alto (capítulos 13-17), incluyendo el lavatorio de pies y la oración sacerdotal. Propósito: "para que creáis que Jesús es el Cristo, el Hijo de Dios, y para que creyendo tengáis vida" (Juan 20:31).',
  44: 'Autor: Lucas (médico y compañero de Pablo). Fecha: ~62-64 d.C.\n\nHechos de los Apóstoles (también llamado "Los Hechos del Espíritu Santo") es la continuación del evangelio de Lucas. Narra el nacimiento y expansión de la iglesia primitiva desde Jerusalén hasta Roma. Capítulos 1-7: la ascensión de Jesús, Pentecostés (el derramamiento del Espíritu Santo), el discurso de Pedro, la vida de la comunidad cristiana primitiva, el martirio de Esteban. Capítulos 8-12: la expansión a Samaria y Judea, la conversión de Saulo (Pablo), la visión de Pedro y la conversión de Cornelio (los gentiles). Capítulos 13-28: los tres viajes misioneros de Pablo, el concilio de Jerusalén, el arresto de Pablo, su defensa ante Félix, Festo y Agripa, el viaje a Roma y el naufragio. Versículo clave: "Recibiréis poder cuando haya venido sobre vosotros el Espíritu Santo, y me seréis testigos" (Hechos 1:8).',
  45: 'Autor: Pablo (apóstol). Fecha: ~57 d.C.\n\nRomanos es la carta más importante de Pablo, una exposición sistemática del evangelio. Pablo escribe a la iglesia en Roma, que no había visitado. Temas principales: Justificación por la fe (capítulos 1-5): todos han pecado, pero Dios justifica al pecador por la fe en Cristo, no por obras de la Ley (Romanos 3:23-24). Santificación (capítulos 6-8): el creyente muere al pecado y vive en el Espíritu. Soberanía de Dios (capítulos 9-11): la elección de Israel y los gentiles en el plan de Dios. Vida práctica (capítulos 12-16): la transformación del creyente, los dones espirituales, la sumisión a las autoridades, la libertad cristiana y la unidad. Versículos clave: "No me avergüenzo del evangelio, porque es poder de Dios para salvación" (Romanos 1:16), "Por gracia sois salvos por medio de la fe" (Efesios 2:8, paralelo).',
  46: 'Autor: Pablo (apóstol). Fecha: ~55 d.C.\n\n1 Corintios aborda los problemas de la iglesia en Corinto, una ciudad portuaria inmoral. Pablo responde a problemas reportados y preguntas que la iglesia le había hecho: Divisiones y facciones (capítulos 1-4), inmoralidad sexual (capítulo 5), litigios entre hermanos (capítulo 6), el matrimonio y la soltería (capítulo 7), la comida ofrecida a ídolos (capítulos 8-10), el velo de la mujer (capítulo 11), la Cena del Señor (capítulo 11), los dones espirituales (capítulos 12-14), la resurrección (capítulo 15, el capítulo más extenso sobre la resurrección), y la colecta para los santos (capítulo 16). Incluye el famoso "himno del amor" (1 Corintios 13): "El amor es paciente, es bondadoso... El amor nunca deja de ser".',
  47: 'Autor: Pablo (apóstol). Fecha: ~56 d.C.\n\n2 Corintios es la carta más autobiográfica y apasionada de Pablo. Escrita poco después de 1 Corintios, defiende su ministerio apostólico contra críticos que lo acusaban de ser indigno. Describe la naturaleza del ministerio cristiano: somos "olor de Cristo" (capítulo 2), ministros del nuevo pacto (capítulo 3), tenemos este tesoro en vasos de barro (capítulo 4), andamos por fe no por vista (capítulo 5). Habla del "aguijón en la carne" que lo mantiene humilde (capítulo 12). Incluye enseñanzas sobre la generosidad en la ofrenda (capítulos 8-9): "Dios ama al dador alegre". Termina con la exhortación a examinarse a sí mismos y el saludo trinitario: "La gracia del Señor Jesucristo, el amor de Dios y la comunión del Espíritu Santo" (2 Corintios 13:14).',
  48: 'Autor: Pablo (apóstol). Fecha: ~49-50 d.C.\n\nGálatas es la carta más apasionada de Pablo, escrita a las iglesias de Galacia (posiblemente escritas antes del concilio de Jerusalén). Pablo defiende el evangelio de la justificación solo por la fe, no por las obras de la Ley. Judíos cristianos (judaizantes) enseñaban que los gentiles debían circuncidarse y guardar la Ley de Moisés para ser salvos. Pablo se opone firmemente: el evangelio que él predicó vino por revelación directa de Cristo (capítulo 1), Pedro mismo fue confrontado por Pablo en Antioquía por su hipocresía (capítulo 2). Usa el ejemplo de Abraham, quien fue justificado por fe antes de la Ley (capítulo 3), y la alegoría de Agar y Sara (capítulo 4). El creyente es libre en Cristo del yugo de la Ley (capítulo 5), pero no debe usar la libertad para pecar sino para servir por amor. Versículo clave: "El fruto del Espíritu es amor, gozo, paz..." (Gálatas 5:22-23).',
  49: 'Autor: Pablo (apóstol). Fecha: ~60-62 d.C.\n\nEfesios revela el plan eterno de Dios para unificar todas las cosas en Cristo. Pablo escribe desde la prisión (junto con Filipenses, Colosenses y Filemón, las "cartas de la prisión"). Primera parte (capítulos 1-3): doctrina. Dios nos bendijo con toda bendición espiritual en Cristo (capítulo 1), por gracia somos salvos mediante la fe (capítulo 2:8-9), el misterio de Cristo revelado: los gentiles son coherederos del mismo cuerpo (capítulo 3). Segunda parte (capítulos 4-6): práctica. Andad dignos de vuestra vocación (capítulo 4), vestíos del nuevo hombre (capítulo 4), andad en amor (capítulo 5), las relaciones familiares: esposos y esposas, padres e hijos, amos y siervos (capítulos 5-6), la armadura de Dios para la guerra espiritual (capítulo 6). Es una carta de altura celestial con aplicación terrenal.',
  50: 'Autor: Pablo (apóstol). Fecha: ~60-62 d.C.\n\nFilipenses es la carta más gozosa de Pablo, escrita desde la prisión a la iglesia en Filipos (la primera iglesia fundada por Pablo en Europa, en el segundo viaje misionero). Pablo agradece por su participación en el evangelio y los anima a tener unidad y humildad. Incluye el himno de Cristo (Filipenses 2:5-11), uno de los pasajes más importantes del NT sobre la kenosis (abnegación) de Cristo: "siendo en forma de Dios, no estimó el ser igual a Dios como cosa a que aferrarse, sino que se despojó a sí mismo, tomando forma de siervo". Pablo habla de su deseo de partir para estar con Cristo, pero es necesario que permanezca (capítulo 1). Advierte contra los perros (judaizantes). Versículos famosos: "Todo lo puedo en Cristo que me fortalece" (Filipenses 4:13) y "El gozo del Señor es vuestra fortaleza" (Nehemías 8:10, concepto similar).',
  51: 'Autor: Pablo (apóstol). Fecha: ~60-62 d.C.\n\nColosenses fue escrita para combatir una herejía temprana en Colosas (una mezcla de legalismo judío, filosofía griega y misticismo). Pablo proclama la supremacía absoluta de Cristo: "Él es la imagen del Dios invisible, el primogénito de toda creación, por medio de él fueron creadas todas las cosas... él es antes de todas las cosas, y todas las cosas en él subsisten" (Colosenses 1:15-17). En Cristo están escondidos todos los tesoros de la sabiduría y el conocimiento (capítulo 2). Los creyentes han muerto con Cristo y resucitado con él; deben buscar las cosas de arriba y mortificar la naturaleza terrenal (capítulo 3). Incluye instrucciones para las relaciones familiares y la conducta cristiana. Termina con saludos personales.',
  52: 'Autor: Pablo (apóstol). Fecha: ~50-51 d.C.\n\n1 Tesalonicenses es probablemente la primera carta escrita por Pablo (desde Corinto). Pablo agradece por la fe, el amor y la esperanza de los tesalonicenses, quienes se convirtieron del paganismo en medio de gran aflicción. Los anima a vivir en santidad y pureza sexual (capítulo 4). Enseña sobre la segunda venida de Cristo (parusía): los muertos en Cristo resucitarán primero, luego los vivos serán arrebatados juntamente con ellos para encontrarse con el Señor en el aire (1 Tesalonicenses 4:16-17). Les recuerda que el día del Señor vendrá como ladrón en la noche, y los exhorta a estar alerta y vivir como hijos de la luz. "Estad siempre gozosos. Orad sin cesar. Dad gracias en todo" (1 Tesalonicenses 5:16-18).',
  53: 'Autor: Pablo (apóstol). Fecha: ~51-52 d.C.\n\n2 Tesalonicenses fue escrita poco después de 1 Tesalonicenses para corregir malentendidos sobre el Día del Señor. Algunos creyentes pensaban que ya había llegado, tal vez debido a persecuciones intensas. Pablo explica que antes deben venir la apostasía y la manifestación del "hombre de pecado" (el anticristo) que se sienta en el Templo como Dios (capítulo 2). Les pide que no se dejen engañar por falsas cartas o profecías. También corrige a los ociosos: algunos habían dejado de trabajar porque pensaban que Cristo volvería pronto, Pablo ordena: "Si alguno no quiere trabajar, tampoco coma" (2 Tesalonicenses 3:10). Los anima a perseverar y orar.',
  54: 'Autor: Pablo (apóstol). Fecha: ~62-64 d.C.\n\n1 Timoteo es una carta pastoral (junto con 2 Timoteo y Tito) escrita a Timoteo, hijo espiritual de Pablo, quien supervisaba la iglesia en Éfeso. Pablo instruye sobre el orden en la iglesia: combatir falsas doctrinas (capítulo 1), la oración por todos los hombres (capítulo 2), los requisitos para obispos (sobreintendentes) y diáconos (capítulo 3), cómo conducirse en la casa de Dios, el ejercicio de la piedad, el cuidado de las viudas, el respeto a los ancianos (capítulo 5), los peligros del amor al dinero (capítulo 6). Versículos clave: "Ejercítate para la piedad" (1 Timoteo 4:7), "Ninguno tenga en poco tu juventud" (1 Timoteo 4:12), "La piedad con contentamiento es gran ganancia" (1 Timoteo 6:6), "Porque el amor al dinero es la raíz de todos los males" (1 Timoteo 6:10).',
  55: 'Autor: Pablo (apóstol). Fecha: ~66-67 d.C.\n\n2 Timoteo es la última carta de Pablo, escrita desde la prisión en Roma, poco antes de su martirio (probablemente bajo Nerón). Es su testamento espiritual. Pablo sabe que su partida está cerca: "He peleado la buena batalla, he acabado la carrera, he guardado la fe" (2 Timoteo 4:7). Exhorta a Timoteo a avivar el fuego del don de Dios, a no tener espíritu de cobardía, a predicar la Palabra a tiempo y fuera de tiempo, a soportar las aflicciones como buen soldado de Cristo. Le advierte que en los últimos días los hombres serán amadores de sí mismos, y que los falsos maestros tendrán apariencia de piedad pero negarán la eficacia de ella. Le pide que venga pronto y que traiga el capote y los pergaminos. Momento conmovedor: "Demas me ha desamparado... el Señor estuvo a mi lado y me fortaleció" (2 Timoteo 4:10, 17).',
  56: 'Autor: Pablo (apóstol). Fecha: ~63-64 d.C.\n\nTito fue escrita a Tito, otro colaborador de Pablo, que estaba en la isla de Creta organizando las iglesias. Pablo le instruye sobre la designación de ancianos (capítulo 1), la enseñanza de la sana doctrina a diferentes grupos: ancianos, ancianas, jóvenes, siervos (capítulo 2), y la relación con las autoridades y la práctica de buenas obras (capítulo 3). El fundamento teológico: "Porque la gracia de Dios se ha manifestado para salvación a todos los hombres, enseñándonos que, renunciando a la impiedad y a los deseos mundanos, vivamos en este siglo sobria, justa y piadosamente" (Tito 2:11-12). Versículo clave: "No por obras de justicia que nosotros hubiéramos hecho, sino por su misericordia nos salvó" (Tito 3:5).',
  57: 'Autor: Pablo (apóstol). Fecha: ~60-62 d.C.\n\nFilemón es la carta más personal y corta de Pablo (solo 25 versículos). Escrita desde la prisión, Pablo intercede por Onésimo, un esclavo de Filemón que había huido y posiblemente robado a su amo. Onésimo se encontró con Pablo en prisión y se convirtió al evangelio. Pablo lo envía de vuelta a Filemón con esta carta, pidiendo que lo reciba "no ya como esclavo, sino como hermano amado" (versículo 16). Pablo se ofrece a pagar cualquier deuda que Onésimo deba. Es una bella demostración del evangelio en acción: cómo la fe en Cristo transforma las relaciones sociales. También muestra el principio de la intercesión: así como Pablo intercede por Onésimo, Cristo intercede por nosotros.',
  58: 'Autor: Tradicionalmente Pablo (incierto; posiblemente Bernabé, Apolos, Priscila o Clemente). Fecha: ~64-68 d.C.\n\nHebreos es una carta profunda que demuestra la superioridad de Cristo. Escrita a cristianos judíos tentados a volver al judaísmo por la persecución. Estructura: Cristo es superior a los profetas (capítulo 1), a los ángeles (capítulos 1-2), a Moisés (capítulo 3), al sacerdocio de Aarón (capítulos 4-7). Cristo es el Sumo Sacerdote según el orden de Melquisedec, que se ofreció a sí mismo de una vez para siempre (capítulo 7-10). La fe es el tema central (capítulo 11: el "salón de la fe" con héroes del AT). La disciplina del Señor (capítulo 12). Exhortaciones prácticas (capítulo 13). Versículos clave: "Jesucristo es el mismo ayer, hoy y por los siglos" (Hebreos 13:8). "Teniendo un gran Sumo Sacerdote... acerquémonos confiadamente al trono de la gracia" (Hebreos 4:14-16).',
  59: 'Autor: Santiago (hermano de Jesús, líder de la iglesia de Jerusalén). Fecha: ~45-50 d.C.\n\nSantiago es una carta práctica y directa sobre la fe vivida. Dirigida a las doce tribus dispersas. Enfatiza que la fe genuina produce obras: "Así como el cuerpo sin espíritu está muerto, así también la fe sin obras está muerta" (Santiago 2:26). Temas: las pruebas producen paciencia y perfección (capítulo 1), no solo oidores sino hacedores de la palabra (capítulo 1), la fe sin obras es muerta (capítulo 2), el poder de la lengua (capítulo 3), la sabiduría de lo alto (capítulo 3), las pasiones que producen conflictos (capítulo 4), la paciencia en el sufrimiento y la oración de fe (capítulo 5). Versículos clave: "Contad por sumo gozo cuando caigáis en diversas pruebas" (Santiago 1:2), "El que duda es semejante a la onda del mar" (Santiago 1:6).',
  60: 'Autor: Pedro (apóstol). Fecha: ~62-64 d.C.\n\n1 Pedro fue escrita a cristianos dispersos en Asia Menor que sufrían persecución. Pedro los alienta recordándoles su esperanza viva mediante la resurrección de Cristo (capítulo 1). Los llama "linaje escogido, real sacerdocio, nación santa, pueblo adquirido por Dios" (1 Pedro 2:9). Enseña cómo vivir en medio del sufrimiento: como siervos, como esposas y esposos, como comunidad que se ama profundamente. Jesús es nuestro ejemplo en el sufrimiento: "quien llevó él mismo nuestros pecados en su cuerpo sobre el madero" (1 Pedro 2:24). El bautismo nos salva (capítulo 3). El amor cubre multitud de pecados (capítulo 4). Humillarse bajo la poderosa mano de Dios (capítulo 5). Versículo clave: "Sed sobrios y velad; porque vuestro adversario el diablo, como león rugiente, anda alrededor buscando a quien devorar" (1 Pedro 5:8).',
  61: 'Autor: Pedro (apóstol). Fecha: ~64-67 d.C.\n\n2 Pedro es el testamento de Pedro, escrito poco antes de su muerte. Advierte contra los falsos maestros que niegan la segunda venida de Cristo introduciendo herejías destructivas. Pedro llama al crecimiento espiritual mediante la fe, la virtud, el conocimiento, el dominio propio, la paciencia, la piedad, el afecto fraternal y el amor (2 Pedro 1:5-7). Afirma que la Escritura es inspirada por Dios: "los santos hombres de Dios hablaron siendo inspirados por el Espíritu Santo" (2 Pedro 1:21). Los falsos maestros serán juzgados (capítulo 2). El día del Señor vendrá como ladrón, y esperamos cielos nuevos y tierra nueva (capítulo 3). Versículo clave: "Tenemos también la palabra profética más segura" (2 Pedro 1:19).',
  62: 'Autor: Juan (el apóstol). Fecha: ~85-95 d.C.\n\n1 Juan es una carta de seguridad y comunión. Juan escribe para que los creyentes tengan certeza de su salvación y para combatir enseñanzas falsas (probablemente un proto-gnosticismo que negaba que Jesús había venido en carne). Temas: Dios es luz, andar en luz (capítulo 1), Jesucristo es nuestro abogado y propiciación (capítulo 2), el amor fraternal como evidencia de conocer a Dios (capítulos 2-3), el mandamiento de amarnos unos a otros, el Espíritu Santo nos enseña (capítulo 2), Dios es amor (capítulo 4), la fe que vence al mundo (capítulo 5), y el testimonio de Dios acerca de su Hijo. Versículos clave: "Dios es amor" (1 Juan 4:8), "El perfecto amor echa fuera el temor" (1 Juan 4:18), "Estas cosas os he escrito para que sepáis que tenéis vida eterna" (1 Juan 5:13).',
  63: 'Autor: Juan (el apóstol). Fecha: ~85-95 d.C.\n\n2 Juan es la carta más corta de Juan (13 versículos), escrita a "la señora elegida" (posiblemente una iglesia local). Advierte contra recibir en casa o saludar a los falsos maestros que no confiesan que Jesucristo ha venido en carne. Exhorta a andar en la verdad y en el amor, que es andar según los mandamientos de Dios. Un énfasis: permanecer en la doctrina de Cristo. No debemos dar apoyo financiero ni hospitalidad a los que enseñan falsas doctrinas, para no participar de sus malas obras.',
  64: 'Autor: Juan (el apóstol). Fecha: ~85-95 d.C.\n\n3 Juan es la carta más personal de Juan (15 versículos), escrita a Gayo, un creyente fiel. Juan elogia a Gayo por su hospitalidad hacia los hermanos viajeros que predicaban el evangelio, incluso siendo extranjeros. Contrasta a Gayo con Diótrefes, quien amaba tener el primer lugar, no recibía a los apóstoles y hablaba mal de ellos. Juan recomienda a Demetrio, que tenía buen testimonio de todos. Es un breve pero hermoso ejemplo de cómo la hospitalidad y el apoyo mutuo eran esenciales en la iglesia primitiva.',
  65: 'Autor: Judas (hermano de Santiago y de Jesús). Fecha: ~65-80 d.C.\n\nJudas es una carta urgente y severa que advierte contra los falsos maestros que se han infiltrado en la iglesia, convirtiendo la gracia de Dios en libertinaje y negando a Cristo. Judas usa ejemplos del AT: Israel en el desierto, los ángeles que no guardaron su dignidad, Sodoma y Gomorra, Caín, Balaam, Coré. Describe a los falsos maestros como nubes sin agua, árboles sin fruto, olas bravas del mar, estrellas errantes. Termina con una de las doxologías más hermosas del NT: "A aquel que es poderoso para guardaros sin caída y presentaros sin mancha delante de su gloria con gran alegría, al único Dios nuestro Salvador, sea gloria y majestad" (Judas 24-25).',
  66: 'Autor: Juan (el apóstol). Fecha: ~95-96 d.C.\n\nApocalipsis (Revelación de Jesucristo) es el único libro profético del NT, escrito por Juan en el exilio en la isla de Patmos. Comienza con siete cartas a las iglesias de Asia Menor: Éfeso, Esmirna, Pérgamo, Tiatira, Sardis, Filadelfia y Laodicea (capítulos 2-3). Luego, visiones del cielo: el trono de Dios, los 24 ancianos, el Cordero inmolado digno de abrir los siete sellos (capítulos 4-5). Los siete sellos (capítulo 6), las siete trompetas (capítulos 8-11), la mujer y el dragón (capítulo 12), la bestia del mar y la bestia de la tierra (capítulo 13), el Cordero y los 144,000 (capítulo 14), las siete copas de la ira de Dios (capítulos 15-16), la caída de Babilonia la ramera (capítulos 17-18), la cena de las bodas del Cordero (capítulo 19), el milenio y el juicio final (capítulo 20), el nuevo cielo y la nueva tierra, la Nueva Jerusalén (capítulos 21-22). Concluye con la invitación: "El que quiera, tome del agua de la vida gratuitamente" y "Sí, ven pronto, Señor Jesús" (Apocalipsis 22:17, 20).',
};

const Map<int, int> bookChapterCounts = {
  1: 50,
  2: 40,
  3: 27,
  4: 36,
  5: 34,
  6: 24,
  7: 21,
  8: 4,
  9: 31,
  10: 24,
  11: 22,
  12: 25,
  13: 29,
  14: 36,
  15: 10,
  16: 13,
  17: 10,
  18: 42,
  19: 150,
  20: 31,
  21: 12,
  22: 8,
  23: 66,
  24: 52,
  25: 5,
  26: 48,
  27: 12,
  28: 14,
  29: 3,
  30: 9,
  31: 1,
  32: 4,
  33: 7,
  34: 3,
  35: 3,
  36: 3,
  37: 2,
  38: 14,
  39: 4,
  40: 28,
  41: 16,
  42: 24,
  43: 21,
  44: 28,
  45: 16,
  46: 16,
  47: 13,
  48: 6,
  49: 6,
  50: 4,
  51: 4,
  52: 5,
  53: 3,
  54: 6,
  55: 4,
  56: 3,
  57: 1,
  58: 13,
  59: 5,
  60: 5,
  61: 3,
  62: 5,
  63: 1,
  64: 1,
  65: 1,
  66: 22,
};
